apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-server-alpine
    app.kubernetes.io/component: nfs-server-alpine
    app.kubernetes.io/instance: nfs-server-alpine
  name: nfs-server-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: nfs-server-alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: nfs-server-alpine
    spec:
      containers:
      - env:
        - name: SHARED_DIRECTORY
          value: /nfsshare
        - name: VOLUME_COUNT
          value: "100"
        image: itsthenetwork/nfs-server-alpine@sha256:7fa99ae65c23c5af87dd4300e543a86b119ed15ba61422444207efc7abd0ba20
        imagePullPolicy: IfNotPresent
        name: nfs-server-alpine
        ports:
        - containerPort: 2049
          protocol: TCP
        - containerPort: 111
          protocol: TCP
        - containerPort: 111
          protocol: UDP
        startupProbe:
          exec:
            command:
              - pidof
              - rpc.mountd
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - pidof
              - rpc.mountd
        readinessProbe:
          exec:
            command:
              - pidof
              - rpc.mountd
        lifecycle:
          postStart:
            exec:
              command: 
               - "/bin/sh"
               - "-c"
               - >
                 for dir in $(seq ${VOLUME_COUNT}); do mkdir -p $SHARED_DIRECTORY/pv$dir && chmod 777 $SHARED_DIRECTORY/pv$dir; done
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /nfsshare
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
  namespace: nfs-server
  labels:
    app: nfs-server-alpine
spec:
  selector:
    deployment: nfs-server-alpine
  ports:
    - name: nfs
      protocol: TCP
      port: 2049
      targetPort: 2049
    - name: rpcbind-tcp
      protocol: TCP
      port: 111
      targetPort: 111
    - name: rpcbind-udp
      protocol: UDP
      port: 111
      targetPort: 111
    - name: mountd
      protocol: TCP
      port: 20048
      targetPort: 20048
  type: ClusterIP
